name: Release Builder

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: [published]

jobs:
  windows-x86_64-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run Windows Build Script
        run: scripts\build_windows.bat
        shell: cmd

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: OnTheSpot-x86_64.exe
          path: dist/OnTheSpot.exe

      - name: Upload to Release (Windows)
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/OnTheSpot.exe
          asset_name: OnTheSpot-x86_64.exe
          asset_content_type: application/octet-stream

  macos-x86_64-build:
    runs-on: macos-13
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run macOS Build Script
        run: scripts/build_mac.sh
        shell: bash

      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: OnTheSpot-x86_64.dmg
          path: dist/OnTheSpot.dmg

      - name: Upload to Release (macOS)
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/OnTheSpot.dmg
          asset_name: OnTheSpot-x86_64.dmg
          asset_content_type: application/x-apple-diskimage

  macos-arm64-build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run macOS Build Script
        run: scripts/build_mac.sh
        shell: bash

      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: OnTheSpot-arm64.dmg
          path: dist/OnTheSpot.dmg

      - name: Upload to Release (macOS)
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/OnTheSpot.dmg
          asset_name: OnTheSpot-arm64.dmg
          asset_content_type: application/x-apple-diskimage

  linux-x86_64-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y patchelf fuse libfuse2 wget

      - name: Run Linux Build Script
        run: scripts/build_linux.sh
        shell: bash

      - name: Upload Linux Executable
        uses: actions/upload-artifact@v4
        with:
          name: OnTheSpot-x86_64.tar.gz
          path: dist/OnTheSpot.tar.gz

      - name: Upload to Release (Linux)
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/OnTheSpot.tar.gz
          asset_name: OnTheSpot-x86_64.tar.gz
          asset_content_type: application/gzip

  appimage-x86_64-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgssapi-krb5-2 libxcb-cursor0 libxcb-xinerama0 libxcb1 ffmpeg desktop-file-utils fuse patchelf wget

      - name: Run AppImage Build Script
        run: scripts/build_appimage.sh
        shell: bash

      - name: Upload AppImage Executable
        uses: actions/upload-artifact@v4
        with:
          name: OnTheSpot-x86_64.AppImage
          path: dist/OnTheSpot-x86_64.AppImage

      - name: Upload to Release (AppImage)
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/OnTheSpot-x86_64.AppImage
          asset_name: OnTheSpot-x86_64.AppImage
          asset_content_type: application/octet-stream
